#!/usr/bin/env python

from time import sleep

# Get the GPIO Library
import RPi.GPIO as GPIO
 
# Adding code to grab PID and create PIDFILE
# !---   Legacy code for creating a PIDFILE  ---!
# !--- no longer needed.  Left for reference ---!
# !--- Generated by init.d/gpio-startup now. ---!
#import os
#pid = str(os.getpid())
#f = open('/var/run/gpio-startup.pid', 'w')
#f.write(pid)
#f.close()

# setup some names references to the LED's and buttons
# red     = pin 17
# green   = pin 27 (512mb rev2) pin 21 (256mb original)
# blue    = pin 22
 
# using an list to hold the led numbers
leds = [17, 27, 22] 

# Input button is on pin 16 (pin 2 on 512mb; pin 0 on orig 256mb)
button = 16

# Initialize counter
count = 0

# Initialize the board and setup the pins as output and input as needed
GPIO.setmode(GPIO.BCM)

# looping over the list
for n in leds:
    GPIO.setup(n, GPIO.OUT)
 
GPIO.setup(button, GPIO.IN)
 
while 1:
#  if GPIO.input(button):
    GPIO.output(leds[(count - 1) % len(leds)], False)  # Turn LED off
    GPIO.output(leds[count % len(leds)], True)         # Light next LED up
    sleep(0.25)
    sleep(0.0050)
    count += 1
#  else:
#    stopLED = True
#    while stopLED:
#      if not GPIO.input(button):
#        stopLED = False
